TOPFILE := wrapper.bsv
TOPFILE_DIR := ./
TOP_MODULE :=mkMac

BSCINCDIR:= .:common_src/:rtl/common_src/:/home/joyen/bsc/inst/lib/Libraries/

VERILOGDIR := build/verilog
BDIR := build/intermediate
BSVOUTDIR:=build/bin/
BSVBUILDDIR:=build/intermediate/