//
// Generated by Bluespec Compiler, version 2023.01-31-gfdf107c7 (build fdf107c7)
//
// On Mon Aug 14 12:53:22 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// mux                            O    32
// RDY_mux                        O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// mux_a                          I    32
// mux_b                          I    32
// mux_sel                        I     1
//
// Combinational paths from inputs to outputs:
//   (mux_a, mux_b, mux_sel) -> mux
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkmux21(CLK,
	       RST_N,

	       mux_a,
	       mux_b,
	       mux_sel,
	       mux,
	       RDY_mux);
  input  CLK;
  input  RST_N;

  // value method mux
  input  [31 : 0] mux_a;
  input  [31 : 0] mux_b;
  input  mux_sel;
  output [31 : 0] mux;
  output RDY_mux;

  // signals for module outputs
  wire [31 : 0] mux;
  wire RDY_mux;

  // value method mux
  assign mux = mux_sel ? mux_a : mux_b ;
  assign RDY_mux = 1'd1 ;
endmodule  // mkmux21

