//
// Generated by Bluespec Compiler, version 2023.01-31-gfdf107c7 (build fdf107c7)
//
// On Sun Aug 13 20:18:45 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// the_answer                     O    32
// RDY_the_answer                 O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// the_answer_x                   I    32
// the_answer_y                   I    32
// the_answer_z                   I    32
//
// Combinational paths from inputs to outputs:
//   (the_answer_x, the_answer_y, the_answer_z) -> the_answer
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkModuleDeepThought(CLK,
			   RST_N,

			   the_answer_x,
			   the_answer_y,
			   the_answer_z,
			   the_answer,
			   RDY_the_answer);
  input  CLK;
  input  RST_N;

  // value method the_answer
  input  [31 : 0] the_answer_x;
  input  [31 : 0] the_answer_y;
  input  [31 : 0] the_answer_z;
  output [31 : 0] the_answer;
  output RDY_the_answer;

  // signals for module outputs
  wire [31 : 0] the_answer;
  wire RDY_the_answer;

  // value method the_answer
  assign the_answer = the_answer_x + the_answer_y + the_answer_z ;
  assign RDY_the_answer = 1'd1 ;
endmodule  // mkModuleDeepThought

